theme: jekyll-theme-minimal
title: nuova stanza
description: >- # this means to ignore newlines until "baseurl:" 
  タイトル
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shirleylorina
github_username:  shirleylorina
